apiVersion: v1
kind: Namespace
metadata:
  name: pr-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
  namespace: pr-3
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: web
        image: siddharthdoc/demo-app:c141cf5
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-3
  namespace: pr-3
spec:
  selector:
    app: demo-app
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-3
  namespace: pr-3
spec:
  rules:
  - host: pr-3.172.17.5.38.nip.io   # REPLACE YOUR_IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-3
            port:
              number: 80